# -*- generated by 1.0.9 -*-
import da
PatternExpr_210 = da.pat.TuplePattern([da.pat.ConstantPattern('SET_UP')])
PatternExpr_215 = da.pat.BoundPattern('_BoundPattern219_')
PatternExpr_220 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern226_')]), da.pat.TuplePattern([da.pat.ConstantPattern('SET_UP')])])
_config_object = {}
import config
import os
client = da.import_da('Client')
replica = da.import_da('Replica')
clients = []
replicas = []

class Olympus(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._OlympusReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_OlympusReceivedEvent_0', PatternExpr_210, sources=[PatternExpr_215], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, clients, replicas, **rest_494):
        super().setup(clients=clients, replicas=replicas, **rest_494)
        self._state.clients = clients
        self._state.replicas = replicas
        self.output('************Setting Up Olympus***********')
        self._state.clients = self._state.clients
        self._state.replicas = self._state.replicas

    def run(self):
        self.output('*********RUN : Olympus***********')
        PatternExpr_220.match_iter(self._OlympusReceivedEvent_0, _BoundPattern226_=self._state.clients, SELF_ID=self._id)
        self.output('*********Received SET_UP from Client***********')
        self.send(('SET_UP',), to=self._state.clients)

    def main(self):
        pass

def setup_main():
    config.main()

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        setup_main()
        totalReplica = config.readProperty('num_replica')
        totalClients = config.readProperty('num_client')
        replicaHosts = config.readProperty('replica_hosts')
        clientHosts = config.readProperty('client_hosts')
        operationList = config.readProperty('workload[1]')
        replicaBaseName = 'replica_'
        clientBaseName = 'client_'
        for i in range(0, totalClients):
            nodeName = (clientBaseName + str(i))
            clListTemp = self.new(client.Client, num=1, at=nodeName)
            clients.extend(clListTemp)
        for i in range(0, totalReplica):
            nodeName = (replicaBaseName + str(i))
            reListTemp = self.new(replica.Replica, num=1, at=nodeName)
            replicas.extend(reListTemp)
        olympus = self.new(Olympus, num=1)
        print('clients => ', clients)
        print('replicas => ', replicas)
        print('olympus => ', olympus)
        for (rnum, rep) in enumerate(replicas):
            replicaName = (replicaBaseName + str(rnum))
            print('replicaName is : ', replicaName)
            if (rnum == 0):
                prevReplica = None
                nextReplica = replicas[(rnum + 1)]
            elif (rnum == (totalReplica - 1)):
                prevReplica = replicas[(rnum - 1)]
                nextReplica = None
            else:
                nextReplica = replicas[(rnum + 1)]
                prevReplica = replicas[(rnum - 1)]
            print('*********replicaName : ', replicaName, ' prevReplica : ', prevReplica, ', nextReplica : ', nextReplica)
            self._setup(rep, [clients[0], olympus, replicaName, prevReplica, nextReplica])
        for cli in clients:
            self._setup(cli, [operationList, olympus, replicas])
        self._setup(olympus, [clients, replicas])
        self._start(clients)
        self._start(olympus)
        for rep in replicas:
            self._start(rep)
